# Generated by Django 5.1.6 on 2025-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='+996 000 000 000', max_length=20, null=True, unique=True),
        ),
    ]
